# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: "drupal"

# The runtime the application uses.
type: "php:8.1"

# Configuration of the build of this application.
build:
  flavor: composer

# The build-time dependencies of the app.
dependencies:
  php:
    composer/composer: "^2.0"

runtime:
  extensions:
    - newrelic
    - apcu

variables:
  php:
    memory_limit: 256M

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "mysqldb:mysql"
#    solr: 'solrsearch:solr'
#    redis: 'rediscache:redis'

# The configuration of app when it is exposed to the web.
web:
  locations:
    "/":
      # The folder from which to serve static assets, for this location.
      #
      # This is a filesystem path, relative to the application root.
      root: "web"

      # How long to allow static assets from this location to be cached.
      #
      # Can be a time in seconds, or -1 for no caching. Times can be
      # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
      # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
      # 365 days).
      expires: 5m

      # Whether to forward disallowed and missing resources from this
      # location to the application.
      #
      # Can be true, false or a URI path string.
      passthru: "/index.php"

      # Deny access to static files in this location.
      allow: false

      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf|xlsx)$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true

    "/sites/default/files":
      # Allow access to all files in the public files directory.
      allow: true
      expires: 5m
      passthru: "/index.php"
      root: "web/sites/default/files"

      # Do not execute PHP scripts.
      scripts: false

      rules:
        # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
        "^/sites/default/files/(css|js)":
          expires: 2w

# The size of the persistent disk of the application (in MB).
disk: 4096

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -e
    git clone https://soltz:SmnwNM5VPpUxLxw7CDBC@bitbucket.org/rapiddevelopmentgroup/rdg-static.git rdg-platform
    cd rdg-platform && git checkout new-devops2
    chmod +x /app/rdg-platform/setup.sh
    /app/rdg-platform/setup.sh

    unset NPM_CONFIG_PREFIX
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    cd /app/web && yarn && yarn build
  # The deploy hook runs after your application has been deployed and started.
  deploy: |
    cd web
    drush -y cache-rebuild
    drush -y updatedb
  post_deploy: |
    node /app/rdg-platform/visual-diff/index.js

# The mounts that will be performed when the package is deployed.
mounts:
  "/web/sites/default/files": "shared:files/files"
  "/tmp": "shared:files/tmp"
  "/private": "shared:files/private"
  "/drush-backups": "shared:files/drush-backups"

# The configuration of scheduled execution.
crons:
  drupal:
    spec: "H * * * *"
    cmd: "cd web && drush core-cron"
  rdg:
    spec: "H * * * *"
    cmd: "/app/rdg-platform/cron.sh"
  rdg_space_check:
    spec: "H * * * *"
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
          node /app/rdg-platform/js/checkSpace.js
      fi
  stock_import:
    spec: "H 1 * * *"
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        cd web
        drush et:get-inventory
        drush mrs stock
        drush mr stock
        drush mim stock --update
      fi
